spring.application.name=recipe-platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/recipe_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:07Omemeg}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.stat=INFO
logging.level.org.hibernate.engine.internal.StatisticalLoggingSessionEventListener=INFO

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG